stages:
  - static
  - build
  - test
  - deploy
static_python:
  stage: static
  image: python:2
  before_script:
    - pip install tox
  script:
    - tox -e "py2-{flake8,yapf,pylint}"
static_python3:
  stage: static
  image: python:3
  before_script:
    - pip install tox
  script:
    - tox -e "py3-{flake8,yapf,pylint}"
static_robot:
  stage: static
  image: python:2
  before_script:
    - pip install tox
  script:
    - tox -e robot_lint
build:
  stage: build
  image: python:2
  before_script:
    - pip install tox
  script:
    - rm -rf dist
    - tox -e py2-build
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
build3:
  stage: build
  image: python:3
  before_script:
    - pip install tox
  script:
    - rm -rf dist
    - tox -e py3-build
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
test:
  stage: test
  image: python:2
  before_script:
    - pip install tox
  script:
    - tox -e py2
test3:
  stage: test
  image: python:3
  before_script:
    - pip install tox
  script:
    - tox -e py3
deploy:
  stage: deploy
  image: python:2
  before_script:
    - pip install twine
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
    - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    refs:
      - tags
    variables:
      - $PYPI_USERNAME
      - $PYPI_PASSWORD
