stages:
  - test
  - deploy
Python 2.7:
  stage: test
  image: python:2.7
  script:
    - pip install tox
    - tox -e flake8,yapf,pylint,robot_lint,py27
Python 3.6:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox -e py36
deploy:
  stage: deploy
  image: python:2.7
  before_script:
    - pip install twine
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
    - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    refs:
      - tags
    variables:
      - $PYPI_USERNAME
      - $PYPI_PASSWORD
