---
version: '2'
formats:
  - 'epub'
  - 'pdf'
python:
  install:
    - path: '.'
    - requirements: 'requirements.txt'
    - requirements: 'docs/requirements.txt'
build:
  os: 'ubuntu-20.04'
  tools:
    python: '3.9'
  apt_packages:
    - 'libatlas3-base'
    - 'libhdf5-103'
    - 'python3-gps'
    - 'python3-libhamlib2'
sphinx:
  builder: 'html'
  fail_on_warning: true
